// generated by "sampctl package init"
#include <a_samp>
#include <a_mysql>
// #include <sscanf2>
#include <zcmd>
#include <samp_bcrypt>

#include "includes/core/config.inc"
#include "includes/core/database.inc"
#include "includes/core/player.inc"

// #include "includes/systems/economy.inc"
// #include "includes/systems/leveling.inc"
#include "includes/systems/vehicles.inc"
// #include "includes/systems/garage.inc"
// #include "includes/systems/races.inc"

// #include "includes/races/sprint.inc"
// #include "includes/races/circuit.inc"
// #include "includes/races/drift.inc"
// #include "includes/races/drag.inc"
// #include "includes/races/offroad.inc"
// #include "includes/races/motorcycle.inc"

// #include "includes/shops/vehicles.inc"
// #include "includes/shops/tuning.inc"

#include "includes/systems/hud.inc"
#include "includes/dialogs/auth.inc" // includes logic
// #include "includes/dialogs/shop.inc"
// #include "includes/dialogs/garage.inc"

// #include "includes/commands/player.inc"
// #include "includes/commands/race.inc"
#include "includes/commands/vehicle.inc"
// #include "includes/commands/admin.inc"

main() {
    print("San Andreas GP Started!");
}

public OnGameModeInit() {
    SetGameModeText("San Andreas GP | Racing / Freemode");
    Database_Connect();

    AddPlayerClass(0, 2495.33, 1644.80, 10.80, 0.0, 0, 0, 0, 0, 0, 0);
    //             ^ skin, x, y, z, angle, weapons...

    return 1;
}

public OnGameModeExit() {
    Database_Disconnect();
    return 1;
}

public OnPlayerConnect(playerid) {
    Player_OnConnect(playerid);
    return 1;
}

public OnPlayerDisconnect(playerid) {
    Player_OnDisconnect(playerid);

    return 1;
}

public OnPlayerRequestClass(playerid, classid) {
    SetPlayerPos(playerid, 2495.33, 1644.80, 10.80);
    SetPlayerCameraPos(playerid, 2495.33, 1644.80, 10.80);
    SetPlayerCameraLookAt(playerid, 2500.0, 1644.80, 10.80);
    SetPlayerFacingAngle(playerid, 0.0);
    return 1;
}

public OnPlayerSpawn(playerid) {
    if(!IsPlayerLoggedIn(playerid)) {
        TogglePlayerSpectating(playerid, true);
        TogglePlayerSpectating(playerid, false);
        return 0;
    }

    CreatePlayerHUD(playerid);

    SetPlayerInterior(playerid, 0);
    SetPlayerVirtualWorld(playerid, 0);

    new modelID = CurrentVehicle[playerid][vModelID];
    new color1 = CurrentVehicle[playerid][vColor1];
    new color2 = CurrentVehicle[playerid][vColor2];
    new Float:x = CurrentVehicle[playerid][vPos_x];
    new Float:y = CurrentVehicle[playerid][vPos_y];
    new Float:z = CurrentVehicle[playerid][vPos_z];
    new Float:a = CurrentVehicle[playerid][vPos_a];

    new vehicleid = CreateVehicle(modelID, x, y, z, a, color1, color2, -1);
    CurrentVehicle[playerid][vSAMPID] = vehicleid;

    PutPlayerInVehicle(playerid, vehicleid, 0);

    return 1;
}

public OnPlayerEnterVehicle(playerid, vehicleid, ispassenger) {
    //lock em in, 1st param = marker on top of car
    if(vehicleid == CurrentVehicle[playerid][vSAMPID]) {
        SetVehicleParamsForPlayer(vehicleid, playerid, VEHICLE_PARAMS_OFF, VEHICLE_PARAMS_ON);
    }
    return 1;
}

public OnPlayerExitVehicle(playerid, vehicleid) {
    if(vehicleid == CurrentVehicle[playerid][vSAMPID]) {
        PutPlayerInVehicle(playerid, vehicleid, 0);
    }
    return 1;
}
