// generated by "sampctl package init"
#include <a_samp>
#include <a_mysql>
#include <sscanf2>
#include <zcmd>
#include <samp_bcrypt>

#include "includes/core/config.inc"
#include "includes/core/database.inc"
#include "includes/core/player.inc"

// #include "includes/systems/economy.inc"
// #include "includes/systems/leveling.inc"
// #include "includes/systems/vehicles.inc"
// #include "includes/systems/garage.inc"
// #include "includes/systems/races.inc"

// #include "includes/races/sprint.inc"
// #include "includes/races/circuit.inc"
// #include "includes/races/drift.inc"
// #include "includes/races/drag.inc"
// #include "includes/races/offroad.inc"
// #include "includes/races/motorcycle.inc"

// #include "includes/shops/vehicles.inc"
// #include "includes/shops/tuning.inc"

// UI stuff
#include "includes/dialogs/auth.inc"
// #include "includes/dialogs/shop.inc"
// #include "includes/dialogs/garage.inc"

// #include "includes/commands/player.inc"
// #include "includes/commands/race.inc"
// #include "includes/commands/vehicle.inc"
// #include "includes/commands/admin.inc"

main() {
    print("San Andreas GP Started!");
}

public OnGameModeInit() {
    SetGameModeText("San Andreas GP | Racing / Freemode");
    Database_Connect();

    AddPlayerClass(0, 2495.33, 1644.80, 10.80, 0.0, 0, 0, 0, 0, 0, 0);
    //             ^ skin, x, y, z, angle, weapons...

    return 1;
}

public OnGameModeExit() {
    Database_Disconnect();
    return 1;
}

public OnPlayerConnect(playerid) {
    Player_OnConnect(playerid);
    return 1;
}

public OnPlayerDisconnect(playerid, reason) {
    Player_OnDisconnect(playerid, reason);

    return 1;
}

public OnPlayerRequestClass(playerid, classid) {
    SetPlayerPos(playerid, 2495.33, 1644.80, 10.80);
    SetPlayerCameraPos(playerid, 2495.33, 1644.80, 10.80);
    SetPlayerCameraLookAt(playerid, 2500.0, 1644.80, 10.80);
    SetPlayerFacingAngle(playerid, 0.0);
    return 1;
}

public OnPlayerSpawn(playerid) {
    if(!IsPlayerLoggedIn(playerid)) {
        TogglePlayerSpectating(playerid, true);
        TogglePlayerSpectating(playerid, false);
        return 0;
    }

    SetSpawnInfo(playerid, 0, 0, 2495.33, 1644.80, 10.80, 0.0, 0, 0, 0, 0, 0, 0);

    SetPlayerPos(playerid, 2495.33, 1644.80, 10.80);
    SetPlayerFacingAngle(playerid, 0.0);
    SetPlayerInterior(playerid, 0); //outside, 1 = interiors, 5 = jefferson motel, 7 = caligula's casino
    SetPlayerVirtualWorld(playerid, 0); //0 = default world, 1 = isolated dimension, 2 = another isolated dimension (for races)

    // later: spawn them in their last vehicle at last position

    return 1;
}
