// generated by "sampctl package init"
#include <a_samp>
#include <a_mysql>
#include <sscanf2>
#include <zcmd>
#include <bcrypt>

main() {
	print("San Andreas GP Started!");
}

public OnGameModeInit() {
    SetGameModeText("San Andreas GP | Racing / Freemode");
    AddPlayerClass(0, 0.0, 0.0, 5.0, 0.0, 0, 0, 0, 0, 0, 0);
    
    // MySQL_Connect();
    // LoadRaces();
    // LoadVehicles();
    
    return 1;
}

public OnPlayerConnect(playerid) {
    // Check if registered, show login/register dialog
    return 1;
}

public OnPlayerSpawn(playerid) {
    // Spawn player at race selection area
    return 1;
}